spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postman
    username: postgres
    password:

  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  mvc:
#    static-path-pattern: /static/**
#    template
#  jooq:
#    sql-dialect: POSTGRES


